#!/usr/bin/env bash
#displays Best School using while loop 10x
#but on 9th iteration, display hi as well

i=1
while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    ((i++))
done
