#!/usr/bin/env bash
#displays 4 then bad luck from China
#displays 9 then bad luck from Japan
#displays 17 then bad luck from Italy
#displays numbers 1 to 20

i=1
while [ $i -le 20 ]
do
    echo "$i"
    case "$i" in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
	    ;;
    esac
    ((i++))
done
