#!/usr/bin/env bash
#displays hours from 0 to 12
#displays minutes from 1 to 59

hr=0
while [ $hr -lt 13 ]
do
    echo "Hour: $hr"
    min=1
    while [ $min -le 59 ]
    do
        echo "$min"
        ((min++))
    done
    ((hr++))
done
